### PR TITLE
Negative stat factors reduce stat

### PR DESCRIPTION
**Pull request by oorzkws**
Positive factor is (n * (stat * factor)), negative factor is (n / (stat * abs(factor)))

This allows things like reducing cooldowns based on psychic sensitivity via pure XML mods.

### CODE REVIEW

**Comment by legodude17** [comment]
Have you checked if this breaks any existing mods using the ability framework? Especially Psycasts and the Rim-Effect series.

**Comment by oorzkws** [comment]
> Have you checked if this breaks any existing mods using the ability framework? Especially Psycasts and the Rim-Effect series.

Yes, along with searching all github for each statFactor to ensure the values are as expected. Nobody is using negatives.

**Review by erdelf — APPROVED** [review]

**Comment by legodude17** [comment]
Sounds good, then!

**Comment by oorzkws** [comment]
Thanks for the quick review and merge 🚀 I realized my mod that was modifying cooldowns based on psychic sensitivity could only make them longer 😂

**Comment by erdelf** [comment]
I mean, you can make it shorter, just needs to be below 1 and above 0.....

**Comment by oorzkws** [comment]
> I mean, you can make it shorter, just needs to be below 1 and above 0.....

Yes, but statFactors scale on a stat. So even if it's lower than vanilla, as Psychic sensitivity increases so will the cast time. The desired relationship is the inverse of that.

**Pull request merged**
